=== janicky/space-xml-document/space.dtd
<!ELEMENT space (details, planets, satellites, missions?)>

<!-- Details definition -->
<!ELEMENT details (title, description, authors)>
<!ELEMENT title (#PCDATA)>

<!-- Authors definition -->
<!ELEMENT authors (author+)>
<!ELEMENT author (first_name, last_name, id)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT first_name (#PCDATA)>
<!ELEMENT last_name (#PCDATA)>

<!-- Planets -->
<!ELEMENT planets (planet+)>
<!ELEMENT planet (name, symbol, description, discovery_date?, parameters, last_mission?)>
<!ELEMENT symbol (#PCDATA)>
<!ATTLIST planet id ID #REQUIRED
                 typology (gas_giant|ice_giant|ocean_planet|gas_dwarf|rocky_planet) #IMPLIED 
                 satellites IDREFS #IMPLIED>

<!-- Satellites -->
<!ELEMENT satellites (satellite+)>
<!ELEMENT satellite (name, description, discovery_date?, parameters, last_mission?)>
<!ATTLIST satellite id ID #REQUIRED
                    body IDREF #REQUIRED>

<!-- Missions -->
<!ELEMENT missions (mission*)>
<!ELEMENT mission (name, description)>
<!ATTLIST mission id ID #REQUIRED>

<!-- Details, planets and satellites -->
<!ELEMENT description (#PCDATA)>

<!-- Planets and satellites -->
<!ELEMENT name (#PCDATA)>
<!ELEMENT discovery_date (#PCDATA)>
<!ELEMENT parameters (apoapsis, peryapsis, inclination, orbital_period?)>
<!ELEMENT apoapsis (#PCDATA)>
<!ELEMENT peryapsis (#PCDATA)>
<!ELEMENT inclination (#PCDATA)>

<!ELEMENT orbital_period (#PCDATA)>
<!ATTLIST orbital_period type (days|years) #REQUIRED>

<!ELEMENT last_mission EMPTY>
<!ATTLIST last_mission id IDREF #REQUIRED>

=== janicky/space-xml-document/document.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/css" href="styles.css"?>
<!DOCTYPE space SYSTEM "space.dtd">

<space>
    <details>
        <title>Planets and satellites</title>
        <description>Document contains planets, their satellites 
            and optionally missions.</description>
        <authors>
            <author>
                <id>211807</id>
                <first_name>Konrad</first_name>
                <last_name>Jachimstal</last_name>
            </author>
            <author>
                <id>211951</id>
                <first_name>Patryk</first_name>
                <last_name>Janicki</last_name>
            </author>
        </authors>
    </details>
    <!-- struktura z danymi -->
    <!-- słownikowymi -->
    <!-- identyfikatory id="1" -->
    <!--    Mars, 
            Jupiter (galileuszowe), 
            Saturn (pasterskie + Enceladus), 
            Trappist 1e (bez księżyców), 
            Proxima Centauri B (bez księżyców)  -->
    <!--✓   Misja Opportunity, Curiosity -->
    <planets>
        <planet id="EARTH" satellites="LUN">
            <name>Earth</name>
            <symbol>⊕</symbol>
            <description></description>
            <parameters>
                <apoapsis>152100000</apoapsis>
                <peryapsis>147095000</peryapsis>
                <inclination>7.155</inclination>
                <orbital_period type="years">11.862</orbital_period>
            </parameters>
        </planet>
        
        <planet id="MARS" topology="rocky_planet" satellites="DEI|PHO">
            <name>Mars</name>
            <symbol></symbol>
            <description>Mars is the fourth planet from the Sun and the 
                second-smallest planet in the Solar System after Mercury.</description>
            <parameters>
                <apoapsis>249200000</apoapsis>
                <peryapsis>206700000</peryapsis>
                <inclination>5,65</inclination>
                <orbital_period type="days">687</orbital_period>
            </parameters>
            <last_mission id="M2" />
        </planet>

    </planets>

    <!-- struktura z danymi -->
    <!-- istotnymi - elementy -->
    <!-- referncja do identyfikatorów (ref) -->
    <satellites>
        <satellite id="LUN" body="EARTH">
            <name>Lunar</name>
            <description></description>
            <discovery_date>1789-08-28</discovery_date>
            <parameters>
                <apoapsis>405400</apoapsis>
                <peryapsis>362000</peryapsis>
                <inclination>5.145</inclination>
            </parameters>
            <last_mission id="M1" />
        </satellite>
    </satellites>

    <satellites>
        <satellite id="DEI" body="MARS">
            <name>Deimos</name>
            <description></description>
            <discovery_date>1789-08-28</discovery_date>
            <parameters>
                <apoapsis>405400</apoapsis>
                <peryapsis>362000</peryapsis>
                <inclination>5.145</inclination>
            </parameters>
            <last_mission id="M1" />
        </satellite>
    </satellites>

    <missions>
        <mission id="M1">
            <name>Apollo XI</name>
            <description>Apollo 11 was the spaceflight that landed
                the first two people on the Moon. Commander Neil
                Armstrong and lunar module pilot Buzz Aldrin, both
                American, landed the Apollo Lunar Module Eagle on
                July 20, 1969, at 20:17 UTC. </description>
        </mission>

        <mission id="M2">
            <name>Opportunity</name>
            <description>Opportunity was the second of the two 
                rovers launched in 2003 to land on Mars and begin traversing
                the Red Planet in search of signs of past life. The rover is
                still actively exploring the Martian terrain, having far
                outlasted her planned 90-day mission. </description>
        </mission>

        <mission id="M3">
            <name>Curiosity</name>
            <description>Curiosity is a car-sized rover designed to 
                explore the craterGale on Mars as part of NASA's Mars
                Science Laboratory mission (MSL). </description>
        </mission>
    </missions>
</space>
